from __future__ import annotations

"""ArrNexus in-app documentation catalogue.

This is intentionally data-only.  The Help Centre, contextual Help button,
USER_GUIDE.md and documentation audit are all generated from the same source so
new features cannot quietly drift away from their instructions.
"""

from typing import Any


def _as_list(value):
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    return list(value)


def _topic(slug: str, title: str, category: str, summary: str, *, prerequisites=(), setup=(), usage=(), success=(), troubleshooting=(), safety=(), related=()) -> dict[str, Any]:
    return {
        "slug": slug,
        "title": title,
        "category": category,
        "summary": summary,
        "prerequisites": _as_list(prerequisites),
        "setup": _as_list(setup),
        "usage": _as_list(usage),
        "success": _as_list(success),
        "troubleshooting": _as_list(troubleshooting),
        "safety": _as_list(safety),
        "related": _as_list(related),
    }


TOPICS = [
    _topic(
        "getting-started", "Getting started & first deployment", "Start here",
        "Deploy ArrNexus, create the first administrator, connect only the services you actually use, map any virtual-media paths and finish with Stack Readiness.",
        prerequisites=("Docker on a Linux host is the recommended runtime.", "For host-side release validation on Debian/Ubuntu install unzip and python3-venv.", "The ArrNexus container must be able to reach the APIs you intend to connect."),
        setup=("Download a release ZIP or clone the Git repository.", "For a ZIP release, create a local .venv, install requirements.txt and run python validate.py before building Docker.", "Run docker compose config, then docker compose up -d --build.", "Open http://<ARRNEXUS_HOST>:8484. A fresh install redirects Dashboard to first-run setup.", "Create the administrator account, then follow Setup Guide to connect applications, providers, mounts and readiness checks."),
        usage=("Use the public home page before sign-in for architecture, installation and download guidance.", "Use Dashboard for the quick operational snapshot and Stack Readiness when you deliberately want live checks."),
        success=("/api/health returns HTTP 200.", "The container is healthy and the first administrator can sign in.", "Configured integrations report healthy from inside ArrNexus, not merely from your desktop browser."),
        troubleshooting=("If python validate.py reports ModuleNotFoundError, activate a .venv and install requirements.txt; do not pollute Debian system Python.", "If another container is configured as localhost, replace localhost with a Docker DNS name, routable host name or reverse-proxy address.", "Check docker compose logs --tail=300 arrnexus when the application itself fails to start."),
        safety=("Keep ./data private and back it up before major upgrades.", "Do not publish .env, databases, API keys, Debrid tokens or raw diagnostics."),
        related=("onboarding", "connections", "readiness", "release-management"),
    ),
    _topic(
        "onboarding", "Setup Guide / onboarding", "Start here",
        "The guided setup checks the environment, connected applications, provider registry and library/mount assumptions before marking the installation complete.",
        prerequisites=("An administrator account must exist.",),
        setup=("Open Setup Guide from the sidebar or /onboarding.", "Work through environment, applications, providers, mounts and readiness in order.", "Use Connections and Providers for any missing details; return to Setup Guide afterwards."),
        usage=("The wizard is safe to revisit after upgrades; it is not only for first boot.", "Treat warnings as configuration work to review, not permission for ArrNexus to rewrite third-party services automatically."),
        success=("Required checks for the services you actually use are green and setup.complete is recorded.",),
        troubleshooting=("A missing DUMB mount is often a namespace visibility issue; check DUMB namespace help before changing host paths.", "Optional integrations can remain unconfigured without blocking the application."),
        safety=("Detection is advisory. Confirm paths and destinations before changing routing or library mappings."),
    ),
    _topic(
        "authentication", "Sign-in, profiles & access", "Accounts & security",
        "ArrNexus has its own local users. Authentication is independent of Radarr, Sonarr, DUMB, Spotify and other connected systems.",
        prerequisites=("The first administrator is created during first-run setup."),
        setup=("Administrators can add users under Settings → User accounts & request limits.", "Assign admin/user role, request permission and optional daily request limit.", "Each user can change display name/email/password from Profile."),
        usage=("Sign in with username or saved email address.", "Administrator-only pages include Providers, AIOStreams, Stack Readiness configuration and Music API Settings."),
        success=("User can authenticate and sees only actions allowed by their role."),
        troubleshooting=("If a normal user cannot request media, check can_request and daily limit in Settings.", "For lost passwords use the password-recovery guide; SMTP must be configured for emailed reset links."),
        safety=("Do not reuse service API keys as ArrNexus passwords.", "Keep administrator accounts limited to people who need configuration access."),
        related=("password-recovery", "settings"),
    ),
    _topic(
        "dashboard", "Dashboard / Control Centre", "Operations",
        "The Dashboard is a cached operational summary of library counts, DMM backlog, downloads, recent activity, service state and Stack Readiness.",
        prerequisites=("Sign in to ArrNexus."),
        setup=("No separate setup is required; cards populate from whichever integrations are configured."),
        usage=("Use Dashboard for a fast snapshot rather than forcing a live scan on every visit.", "Use the refresh control when you explicitly need a new snapshot.", "Open Stack Readiness for bounded live service verification."),
        success=("Dashboard renders quickly and shows a snapshot age rather than blocking on every external API."),
        troubleshooting=("If a dependency fails, Dashboard should remain available in degraded mode and point you to diagnostics.", "Search Unified Logs for source=performance or slow_request if navigation remains slow."),
        safety=("A cached value may be a few seconds old; use live readiness before making a critical operational decision."),
    ),
    _topic(
        "discover", "Discover & request media", "Discovery & acquisition",
        "Discover combines metadata search with your Arr/media-server context and can hand a selected movie, show or music result into the owning specialist application.",
        prerequisites=("Configure the relevant Radarr/Sonarr/Lidarr connection for the type of media you want to add."),
        setup=("Open Connections and verify the owning Arr application.", "Configure acquisition/provider settings if you want ArrNexus to compare more than one route."),
        usage=("Search by title, inspect existing-library state, choose the intended Arr/library destination and submit the request.", "Use Acquisition/Quality Lab when you need to understand candidate scoring rather than immediately adding a result."),
        success=("The owning Arr accepts the item and ArrNexus records the request/activity trail."),
        troubleshooting=("If a result adds to the wrong instance, review Routing Rules and destination mappings.", "If search is empty, test the upstream Arr/metadata connections and review Unified Logs."),
        safety=("ArrNexus should hand ownership to the correct Arr rather than directly replacing its library database."),
    ),
    _topic(
        "acquisition", "Acquisition strategies & scraping", "Discovery & acquisition",
        "Acquisition compares available Usenet/Debrid candidates and applies the configured strategy while leaving the owning Arr/download client responsible for the final hand-off.",
        prerequisites=("At least one usable Arr application and one acquisition path/provider for meaningful comparisons."),
        setup=("Configure strategy under Settings → Acquisition.", "Verify Prowlarr/indexers and any provider/backend used by that strategy."),
        usage=("Automatic compares acceptable routes; Debrid-first and Usenet-first add explicit fallback order; focused modes can restrict to one side or prefer cached/quality score."),
        success=("Scraping/Acquisition shows the candidate trail, selected route and final hand-off rather than a silent decision."),
        troubleshooting=("No candidates usually means the relevant search backend or indexer is unavailable, not that ArrNexus should invent one.", "Use Quality Lab for release-name/scoring explanations."),
        safety=("Use dry inspection pages before changing acquisition policy for a large live library."),
        related=("quality-lab", "providers", "indexers"),
    ),
    _topic(
        "debrid-dmm", "Debrid / DMM & device linking", "Debrid & virtual media",
        "The Debrid/DMM area connects ArrNexus to supported Debrid workflows and the DMM-originated source media that originally motivated the project.",
        prerequisites=("A supported Debrid account or a DMM/Decypharr workflow if you intend to use these features."),
        setup=("Open Debrid / DMM and choose Connect when device authorization is required.", "Follow the displayed device-code/provider flow until ArrNexus reports the account connected.", "Configure Provider Registry separately when you want provider-neutral AIOStreams/acquisition capabilities."),
        usage=("Use DMM/Debrid source information as input to Inbox review, matching, routing and managed-library linking.",),
        success=("ArrNexus reports the Debrid connection and DMM sources can be inspected without deleting or rewriting them."),
        troubleshooting=("If device authorization expires, restart Connect rather than reusing an old device code.", "If DMM items are missing, verify DUMB/source-root visibility and the namespace guide."),
        safety=("Disconnecting ArrNexus credentials must not delete source media from the provider.", "Undo is designed around ArrNexus-created links, not source deletion."),
        related=("dmm-inbox", "providers", "dumb-namespace"),
    ),
    _topic(
        "dmm-inbox", "DMM Inbox, language checks & bulk imports", "Debrid & virtual media",
        "DMM Inbox reviews existing Debrid/DMM content, matches it to the correct movie/show, groups duplicate sources, evaluates Language Guard and creates managed library links through explicit jobs.",
        prerequisites=("DMM/Debrid source visibility plus the owning Radarr/Sonarr where matching/import is expected.",),
        setup=("Confirm the DUMB/source root and logical library paths under Settings.", "Verify Radarr/Sonarr and optional media-server connections."),
        usage=("Use Check selected languages, Check all unchecked or Force re-check all without starting an import.", "A stale result created under an older Language Guard policy displays Re-check required rather than pretending the source was never checked.", "Manual bulk destinations are typed explicitly (for example TV · BBC and Movies · Kids), so a chosen TV route overrides a bad scanner guess.", "Combined-season videos are redirected to Advanced TV Recovery instead of being imported as a fake single episode."),
        success=("Imports create and record the expected managed-library link and activity trail while the source remains intact.", "Language jobs reach a clear pass/reject/manual-review result and refresh Inbox state."),
        troubleshooting=("If Inbox is slow, inspect performance/slow_request logs and source visibility rather than repeatedly rescanning.", "If an item cannot be matched, use Item Review and the owning Arr search.", "Archive-style names such as Season 6 episode 1 and Season 1 Complete are recognised as TV in v10.3."),
        safety=("Do not bulk import ambiguous matches.", "Delete rejected source is enabled only for a current destructive-safe rejection with no surviving managed-link dependency and an exact provider identity."),
        related=("item-review", "language-guard", "jobs", "libraries", "tv-recovery"),
    ),
    _topic(
        "item-review", "DMM Item Review & Language Guard", "Debrid & virtual media",
        "Item Review is the decision page for one DMM/Debrid source: inferred identity, owning Arr item, destination route, language inspection and import action.",
        prerequisites=("Open an item from DMM Inbox."),
        setup=("Configure Language Guard policy under Settings if you want stream-language enforcement."),
        usage=("Review metadata and destination before importing.", "Run/re-run the language check when stream metadata is not yet known.", "Use replacement search when a source is rejected but the Arr item still needs media."),
        success=("The item shows an explainable state and any import/skip/reject action is recorded."),
        troubleshooting=("Unknown language metadata can fail closed depending on policy; verify ffprobe can inspect the actual media path.", "A failed match should be corrected before creating a link."),
        safety=("When rejected-source cleanup is enabled, ArrNexus deletes only an exactly identified Real-Debrid torrent after the import has been blocked. Ambiguous provider matches are preserved.",),
        related=("language-guard", "dmm-inbox"),
    ),
    _topic(
        "jobs", "Import Jobs & background work", "Library & automation",
        "Jobs track multi-step or asynchronous ArrNexus work so long operations do not disappear behind one HTTP request.",
        prerequisites=("An action that creates an import/background job."),
        setup=("No special setup is required."),
        usage=("Open Import Jobs to see queued/running/completed state and open an individual job for per-item progress."),
        success=("Jobs reach a terminal state with clear per-item results."),
        troubleshooting=("If a job appears stuck, inspect its detail page and Unified Logs before re-running the source action."),
        safety=("Avoid launching duplicate bulk jobs until you know whether the first one completed."),
    ),
    _topic(
        "libraries", "Libraries, logical mounts & filesystem browser", "Library & automation",
        "ArrNexus distinguishes source content, virtual/cache layers and managed Arr/media-server libraries. Logical mounts describe those relationships without assuming the host filesystem is the same as the DUMB namespace.",
        prerequisites=("Know the paths visible to the relevant containers or DUMB mount namespace."),
        setup=("Configure DUMB logical root and library/source mounts in Settings.", "Use the read-only browser to confirm what ArrNexus can actually see before saving a path."),
        usage=("Libraries shows configured/inventoried roots.", "Browser is for inspection and downloading a visible file, not arbitrary filesystem mutation."),
        success=("Movie/TV/music/source paths resolve to the intended namespace and correspond to the owning Arr roots."),
        troubleshooting=("If /mnt/debrid exists inside DUMB but not on the host, read DUMB namespace help; do not replace it with an unrelated host path.", "If a path is invisible, inspect Docker mounts/namespace rather than repeatedly changing ArrNexus mappings."),
        safety=("Browser access is deliberately bounded to configured logical areas. Do not publish screenshots containing private path/user information."),
        related=("dumb-namespace", "routing"),
    ),
    _topic(
        "lists", "Lists, Watchlists & Trakt Device OAuth", "Library & automation",
        "External lists are first-class ArrNexus request sources: titles are identified, previewed, routed to specialist Radarr/Sonarr destinations and optionally acquired through the normal acquisition planner.",
        prerequisites=("Configure the Radarr/Sonarr destinations that may receive list items.", "Private Trakt data requires an underlying Trakt API application. Trakt may currently restrict creation of new API apps; normal account linking in ArrNexus uses Device OAuth."),
        setup=("Open Lists & Watchlists as an administrator.", "For Trakt, place the application Client ID/Secret under Advanced Trakt application setup, then use Connect Trakt for the normal device-code authorization flow.", "Configure only the other list providers you use: TMDb, Plex Watchlist, Simkl, IMDb public lists, RSS/Atom or Custom JSON.", "Create a list definition, choose movie/TV/mixed destinations, acquisition strategy and sync interval, then Preview before scheduled sync."),
        usage=("Device OAuth shows a user code and authorization link; ArrNexus polls until Trakt approves, denies or expires the request.", "Preview separates existing, already requested, would-add and unmatched titles.", "Existing titles are not moved between specialist libraries merely because another list contains them."),
        success=("Trakt shows Connected with the account identity when available, refresh tokens rotate safely, and list runs record totals/adds/errors."),
        troubleshooting=("Authorization pending is normal until the code is approved.", "If Trakt refuses a new connection, review Trakt Settings → Connected Apps because the account may have reached its community-app limit.", "If matching fails, confirm the list exposes external IDs or a clean title/year."),
        safety=("List sync never deletes existing library media.", "Application credentials and per-user OAuth tokens remain masked/private; token replacement is stored atomically."),
        related=("routing", "acquisition", "providers"),
    ),
    _topic(
        "dumb-namespace", "DUMB mount namespace & /proc/<PID>/root", "Library & automation",
        "In DUMB deployments useful virtual mounts can exist inside another process mount namespace. ArrNexus can view those paths through /proc/<PID>/root while keeping logical paths such as /mnt/debrid in the UI.",
        prerequisites=("Docker Compose retains pid: host and SYS_PTRACE where this architecture is required."),
        setup=("Keep the logical DUMB root configured to the path used inside the DUMB/Arr namespace.", "Use Stack Readiness or Setup Guide to confirm an anchor process/PID and namespace visibility."),
        usage=("Continue entering logical paths such as /mnt/debrid/... rather than hard-coding /proc/<PID>/root into every configuration field."),
        success=("ArrNexus can inspect source/library paths that are not directly mounted on the Docker host."),
        troubleshooting=("If namespace discovery breaks after a container restart, refresh readiness/connection state so ArrNexus can find the new PID.", "Do not remove pid: host/SYS_PTRACE just because normal host ls cannot see the mount."),
        safety=("Namespace access is powerful. Keep ArrNexus private and only enable the capability on a host you control."),
    ),
    _topic(
        "routing", "Routing Rules", "Library & automation",
        "Routing Rules decide which configured destination/library should own different media instead of forcing every request into one universal root.",
        prerequisites=("Define the relevant logical library mounts/destinations first."),
        setup=("Open Routing Rules and add only the criteria/destination mappings you need.", "Confirm specialist Radarr/Sonarr/Lidarr instances or roots exist before referencing them."),
        usage=("Review rules when a title is consistently being sent to the wrong library.", "Delete a rule only after checking what falls back to the default route."),
        success=("Item Review/Discover explains the destination that matches the configured rules."),
        troubleshooting=("Unexpected routing often comes from overlapping rules, stale destination names or a missing default root."),
        safety=("Routing changes can affect future imports; preview with one known title before bulk work."),
    ),
    _topic(
        "self-healing", "Self-Healing", "Library & automation",
        "Self-Healing scans for bounded repair/upgrade opportunities and can trigger searches through the owning Arr application rather than directly replacing library databases.",
        prerequisites=("Relevant Arr connections and visible libraries."),
        setup=("Configure Self-Healing settings and enable only the checks you want automated."),
        usage=("Review detected candidates, trigger a search deliberately, and inspect the resulting Arr activity."),
        success=("A candidate has an explainable reason and the owning Arr receives the requested search."),
        troubleshooting=("If nothing is found, confirm the library inventory and Arr missing/cutoff state are visible."),
        safety=("Start with conservative/manual search triggering before enabling broader automation."),
    ),
    _topic(
        "quality-lab", "Quality Lab", "Library & automation",
        "Quality Lab parses release names and shows how ArrNexus policy scores quality, pack type, cache state and other release characteristics.",
        prerequisites=("A release name or acquisition context to evaluate."),
        setup=("Adjust release policy in Settings if the default scoring does not match your priorities."),
        usage=("Paste/inspect a release to understand the score instead of treating selection as a black box."),
        success=("The page explains the parsed attributes and resulting score/recommendation."),
        troubleshooting=("Unusual release names may not expose every attribute; compare with the raw name and Prowlarr result."),
        safety=("Quality Lab is advisory; changing global policy affects future decisions."),
    ),
    _topic(
        "queue", "Download Queue", "Operations",
        "Download Queue aggregates supported acquisition/download activity so you can see which backend owns current work and whether it is progressing.",
        prerequisites=("At least one supported connected backend with queue information."),
        setup=("Verify the backend connection in Connections/its dedicated integration page."),
        usage=("Use source filters to distinguish different acquisition systems."),
        success=("Active items show source/status/progress rather than requiring separate tabs for every backend."),
        troubleshooting=("An empty queue can be correct; verify the source-specific backend before assuming ArrNexus is failing."),
    ),
    _topic(
        "timeline", "Timeline & activity history", "Operations",
        "Timeline groups ArrNexus events around a title/source so decisions and actions can be read in order rather than as disconnected log lines.",
        prerequisites=("Recorded ArrNexus activity for the title/source."),
        setup=("No extra setup."),
        usage=("Open Timeline from an item/job/log context when reconstructing what happened."),
        success=("Events show chronological request/import/routing state."),
        troubleshooting=("If an external service action is missing, also inspect Unified Logs; ArrNexus only records events it can observe."),
    ),
    _topic(
        "connections", "Connections: Radarr, Sonarr, Lidarr, Prowlarr, Seerr", "Connections & integrations",
        "Connections stores the service URL and protected API key/token ArrNexus needs to talk to your specialist applications.",
        prerequisites=("The target service is running and reachable from the ArrNexus container."),
        setup=("Open Connections.", "Enter the service URL as seen from the ArrNexus container, not necessarily the URL used in your desktop browser.", "Copy the target application's API key/token from its own settings and save/test the connection."),
        usage=("Use service-specific pages only after the connection verifies.", "Multiple Arr instances discovered by the environment remain separate destinations."),
        success=("ArrNexus receives the expected authenticated API response and shows version/name where supported."),
        troubleshooting=("Do not use localhost for another container.", "If the browser can reach a service but ArrNexus cannot, check Docker network/DNS/routing from the container.", "A reachable HTML login page is not considered a healthy API connection."),
        safety=("API keys are stored as secrets and should not appear in screenshots or diagnostics."),
        related=("media-servers", "dumb-namespace"),
    ),
    _topic(
        "media-servers", "Jellyfin, Plex, Emby & custom media servers", "Connections & integrations",
        "Jellyfin remains the deepest library integration. Plex and Emby have first-class authenticated connection/health probes, and a custom HTTP connector supports other media servers without executing third-party code.",
        prerequisites=("A reachable media server and the token/API key required by that server."),
        setup=("Jellyfin: save the server URL and API key in Connections.", "Plex: save the Plex URL and X-Plex-Token.", "Emby: save the Emby URL and API key.", "Custom server: provide name, base URL, health path and optional bearer/custom-header/query authentication."),
        usage=("Use Connections/Readiness to verify health. Jellyfin-specific library features only appear where the Jellyfin API is actually implemented."),
        success=("Probe returns a recognized server response/name/version where supported."),
        troubleshooting=("A reverse-proxy landing page is not the same as a protected API response.", "For Plex/Emby, confirm the token is valid and the configured base URL reaches the actual server API."),
        safety=("Custom connectors perform bounded HTTP probes only; do not put arbitrary scripts/plugins into ArrNexus."),
    ),
    _topic(
        "providers", "Provider Registry", "Connections & integrations",
        "Provider Registry makes ArrNexus provider-neutral: Real-Debrid is one option among Debrid, Usenet and streaming services that can coexist.",
        prerequisites=("A provider account only for providers you choose to enable."),
        setup=("Open Providers as an administrator.", "Enable the provider, fill only its required credential fields and save.", "Leave optional providers disabled instead of entering placeholder values."),
        usage=("Provider capabilities feed acquisition/AIOStreams planning. Existing AIOStreams credentials are preserved where the bridge is designed to avoid overwrites."),
        success=("Enabled providers show configured state without rendering raw credentials."),
        troubleshooting=("If a provider uses username/password, client ID or encoded token rather than an API key, use the fields shown for that provider instead of forcing one credential shape."),
        safety=("Secrets are masked. Do not paste provider credentials into logs, screenshots or GitHub issues."),
        related=("aiostreams", "acquisition"),
    ),
    _topic(
        "infinidysk", "InfiniDysk / NzbDAV telemetry", "Connections & integrations",
        "InfiniDysk gives ArrNexus native Usenet/download telemetry, queue/history and bounded operational actions where supported by the upstream service.",
        prerequisites=("An InfiniDysk/NzbDAV deployment and the URL/credential expected by its API."),
        setup=("Configure the InfiniDysk connector in the relevant connection/ecosystem settings.", "Verify authenticated API behaviour rather than a frontend page."),
        usage=("Select telemetry window and media filter; health, queue, history and overview data are fetched concurrently and cached briefly."),
        success=("Overview/queue/history render without leaking credentials and the page reports snapshot age."),
        troubleshooting=("If /api/infinidysk/live is slow, check upstream latency and performance logs.", "If only a web UI loads, confirm the API URL/credential."),
        safety=("Operational actions are explicit; inspect the target before triggering an upstream action."),
    ),
    _topic(
        "decypharr", "Decypharr", "Connections & integrations",
        "Decypharr is the Debrid/torrent-side integration in the reference DUMB architecture. ArrNexus verifies the protected API and exposes relevant torrents/repairs/Arr context.",
        prerequisites=("A Decypharr instance reachable from ArrNexus and its token/credential."),
        setup=("Save the Decypharr URL and protected credential in the supported connector settings."),
        usage=("Use the dedicated Decypharr page for visibility and bounded repair context."),
        success=("Authenticated API state/version is visible; a login/frontend page alone is not accepted as healthy."),
        troubleshooting=("401/403 normally means the Bearer/API token is wrong or missing.", "Network failures require checking container-to-service routing."),
        safety=("Do not expose Decypharr tokens in diagnostics or screenshots."),
    ),
    _topic(
        "indexers", "Prowlarr Indexers", "Connections & integrations",
        "Indexer management exposes Prowlarr-backed state and supported controls such as enabled state, priority, RSS, automatic search and interactive search.",
        prerequisites=("A verified Prowlarr connection."),
        setup=("Add Prowlarr URL/API key under Connections."),
        usage=("Review/edit an indexer conservatively. ArrNexus sends the full object when required instead of constructing a destructive partial replacement.", "For Sonarr TV releases ArrNexus uses seriesId + seasonNumber and merges/deduplicates results."),
        success=("Saved changes survive a Prowlarr re-read and interactive results correspond to the intended movie/season."),
        troubleshooting=("DUMB or another manager may restore routing-sensitive indexer values after you edit them; check external ownership before assuming ArrNexus ignored the change."),
        safety=("Changing Prowlarr affects multiple Arr applications; record existing values before broad edits."),
    ),
    _topic(
        "music-hub", "Music Hub", "Music",
        "Music Hub combines clearly-labelled discovery sources with Lidarr hand-off and optional per-user Spotify personal data.",
        prerequisites=("Lidarr for managed music acquisition; optional provider application credentials for richer catalogue sources."),
        setup=("Configure Music API Settings for Spotify/SoundCloud/Jamendo/Last.fm as needed.", "Verify Lidarr connection/root for add/search actions."),
        usage=("Choose source and search type, inspect featured/trend data, open artist detail and hand a selected artist/album to Lidarr."),
        success=("Provider ownership is labelled honestly; optional provider failure does not take down the whole Music page."),
        troubleshooting=("If a catalogue URL points at example.com/example.invalid, ArrNexus rejects it; configure a real provider instead.", "If artist pages are slow, check performance logs for /music/artist and upstream MusicBrainz/Lidarr latency."),
        safety=("External music catalogues are discovery sources; acquisition ownership stays with Lidarr/Prowlarr."),
        related=("music-api-settings", "spotify"),
    ),
    _topic(
        "music-api-settings", "Music API Settings", "Music",
        "Administrator page for application-level Spotify, SoundCloud, Jamendo and Last.fm credentials. These are separate from an individual user's Spotify OAuth link.",
        prerequisites=("Administrator access and developer credentials from the provider you choose to enable."),
        setup=("Open Music API Settings from the sidebar.", "Enter only the provider credentials you actually use.", "For Spotify, register the exact callback shown by ArrNexus in the Spotify Developer Dashboard, then save Client ID/Secret and callback URI."),
        usage=("After Spotify app credentials are saved, each ArrNexus user links their own account from Music Hub → Spotify → Connect Spotify."),
        success=("The page reports configured state without displaying saved secrets and Music Hub can use the provider."),
        troubleshooting=("Spotify INVALID_REDIRECT_URI means the URI registered with Spotify does not exactly match the URI ArrNexus sends.", "SoundCloud/Jamendo/Last.fm failures should be checked against the provider's current developer credentials and Unified Logs."),
        safety=("Leave secret fields blank to keep an existing saved secret; never paste them into support screenshots."),
        related=("spotify",),
    ),
    _topic(
        "spotify", "Spotify app setup & per-user OAuth", "Music",
        "Spotify has two layers in ArrNexus: application credentials enable catalogue/API access; per-user OAuth grants personal saved music, playlists, top items and recent listening.",
        prerequisites=("A Spotify developer application, Client ID and Client Secret.", "For remote ArrNexus, a public HTTPS callback address.", "Spotify Development Mode currently requires the app owner to have Premium and each authenticated user to be on the app allowlist; check Spotify's current official quota-mode documentation because these rules can change."),
        setup=("Open Music API Settings and copy the callback URI ArrNexus shows. For this application it ends with /music/spotify/callback.", "In Spotify Developer Dashboard → your app → Settings, add that exact Redirect URI. Do not add/remove a trailing slash unless ArrNexus shows it.", "Save the Spotify Client ID and Client Secret in ArrNexus.", "In Spotify Development Mode, add the intended Spotify account under Users Management/allowlist.", "Open Music Hub → Spotify and click Connect Spotify, approve the scopes, and let Spotify redirect back to ArrNexus."),
        usage=("Each ArrNexus profile links Spotify independently. Disconnecting one profile does not remove the shared application credentials."),
        success=("Music Hub changes from 'app ready — account not linked' to a linked profile and loads personal shelves such as saved tracks/albums/playlists/top/recent data."),
        troubleshooting=("INVALID_REDIRECT_URI: compare the two callback strings character-for-character and require HTTPS except explicit 127.0.0.1/[::1] loopback development.", "403 after successful login in Development Mode: confirm that Spotify user is allowlisted and the app owner still meets Spotify's current Premium requirement.", "OAuth state validation error: start Connect Spotify again; do not reuse an old callback URL.", "429: Spotify rate/quota limits are upstream; retry later and inspect the returned reason."),
        safety=("The Client Secret and refresh tokens are sensitive. ArrNexus stores them as secret settings and must not print them in UI/logs."),
        related=("music-api-settings", "music-hub"),
    ),
    _topic(
        "ecosystem", "Ecosystem & Community Connector SDK", "Connections & integrations",
        "Ecosystem manages data-defined connectors around the DUMB stack and can install supported connector definitions without executing arbitrary third-party Python code.",
        prerequisites=("A connector definition only if you are extending beyond built-in integrations."),
        setup=("Review built-in connector state first.", "For a community connector/provider, install only the supported JSON/data definition format."),
        usage=("Probe enabled connectors and inspect their status from one place."),
        success=("The expected authenticated/status response is parsed and displayed."),
        troubleshooting=("If a connector returns HTML where JSON/API data is expected, correct the API endpoint rather than weakening health verification."),
        safety=("Treat community definitions as untrusted data and review URLs/credential fields before enabling them."),
    ),
    _topic(
        "aiostreams", "AIOStreams Bridge", "Connections & integrations",
        "The AIOStreams Bridge manages one AIOStreams user configuration safely: verify, fetch full config, generate a masked auto-wire preview, reject stale previews, back up before PUT, verify after write and support rollback.",
        prerequisites=("A running AIOStreams instance and an AIOStreams user UUID/alias plus password or encryptedPassword.", "Optional Prowlarr/providers in ArrNexus if you want Auto-Wire to reuse them."),
        setup=("Create/save an AIOStreams user configuration first.", "In ArrNexus → AIOStreams enter Base URL, UUID/alias and credential.", "Verify reachability and authenticated User API access before generating a preview."),
        usage=("Generate Auto-Wire Preview and inspect every change before Apply.", "Apply only a fresh preview. ArrNexus rechecks the digest, creates a private pre-write backup, sends the full config and verifies the result.", "Use Search diagnostics with a movie/series ID; sensitive playback URLs/headers are redacted.", "Rollback creates another safety backup before restoring the selected configuration."),
        success=("Reachable, authenticated and configured checks are green; Apply preserves unrelated AIOStreams settings and backups are available."),
        troubleshooting=("Stale preview refusal is a safety PASS: regenerate preview after any remote AIOStreams change.", "Reachable but not authenticated usually means UUID/alias/credential is wrong.", "If Prowlarr wiring is absent, verify ArrNexus has both Prowlarr URL and API key."),
        safety=("AIOStreams PUT is a full replacement operation, so never bypass preview/digest/backup protections.", "Search diagnostics must not expose Authorization, cookies, proxy headers or playback URLs."),
        related=("providers",),
    ),
    _topic(
        "aiometadata", "AIOMetadata", "Connections & integrations",
        "v10.2 adds a managed AIOMetadata connection for service health, masked per-user configuration visibility, explicit manifest verification and AIOStreams relationship checks.",
        prerequisites=("A reachable AIOMetadata instance; user UUID/alias and password only when you want per-user configuration visibility."),
        setup=("Open AIOMetadata and save its base URL.", "Optionally save the user UUID/alias and password.", "If you want manifest verification, paste the exact generated manifest URL; ArrNexus does not invent compressed configuration URLs."),
        usage=("Use the health card to verify /health.", "Inspect masked user configuration and whether the current AIOStreams user configuration references the same AIOMetadata host."),
        success=("Health responds successfully and any requested user configuration is returned as JSON with sensitive fields masked."),
        troubleshooting=("A healthy service with unreadable user config usually means the UUID/password is wrong or the API path is unavailable.", "If AIOStreams is not linked, verify its active user configuration rather than forcing a write from AIOMetadata."),
        safety=("ArrNexus keeps AIOMetadata authoritative and does not overwrite its remote configuration from this page.", "Secrets are never rendered raw."),
        related=("aiostreams", "providers"),
    ),
    _topic(
        "readiness", "Stack Readiness", "Operations",
        "Stack Readiness deliberately performs bounded live verification of configured services, environment, provider and mount assumptions; it is deeper than the cached Dashboard snapshot.",
        prerequisites=("Administrator access."),
        setup=("Configure the services/providers/mounts you actually use before expecting a complete score."),
        usage=("Open Readiness when commissioning, after an upgrade or when a workflow fails.", "Refresh for a live check instead of using it as the page you repeatedly click during normal navigation."),
        success=("Required pieces for your chosen stack are green and warnings explain optional/missing capabilities."),
        troubleshooting=("A slow Readiness page normally means one or more external APIs are timing out; inspect Server-Timing/performance logs and test those connections individually."),
        safety=("Readiness reports state; it does not grant permission to rewrite third-party configurations."),
    ),
    _topic(
        "problem-centre", "Problem Centre", "Operations",
        "Problem Centre turns detected broken links, missing media and other diagnosable conditions into a focused work queue.",
        prerequisites=("Visible managed libraries and whichever Arr services are needed to classify the problem."),
        setup=("No separate setup beyond correct libraries/connections."),
        usage=("Review the problem reason and owning service before choosing repair/search actions."),
        success=("Each issue has enough context to decide whether ArrNexus, the Arr application, mount layer or provider should own the fix."),
        troubleshooting=("If it takes several seconds, inspect slow_request logs; Problem Centre shares a cached broken-link scan with Maintenance."),
        safety=("Prefer explicit bounded repairs. Do not delete source media merely because a managed-library link is broken."),
    ),
    _topic(
        "maintenance", "Maintenance, repair & housekeeping", "Operations",
        "Maintenance combines repair context with filesystem/source/link/import inventory work, Library Consolidation and v10.2 dependency-protected provider duplicate cleanup.",
        prerequisites=("Correct source/library visibility."),
        setup=("No separate setup; configure backups under Settings."),
        usage=("Inspect broken links/source mappings first, then run a specific repair action.", "Open Library Consolidation to scan every managed movie/TV symlink and preview duplicate groups before applying cleanup.", "Open Provider Duplicate Cleanup to review redundant symlinks and exact provider sources with surviving-link dependency protection.", "Use Diagnostics when collecting support information."),
        success=("Repair changes only the intended managed link/state and the action is logged.", "Consolidation keeps one highest-ranked valid link per movie part/episode, asks the owning Radarr/Sonarr item to rescan, and can optionally remove only provider sources made unreferenced by that exact operation."),
        troubleshooting=("If Maintenance is slow, search Unified Logs for slow_request GET /maintenance and verify filesystem/network mounts are responsive.", "If a consolidation preview becomes stale, run a fresh preview; ArrNexus refuses to apply a changed library plan."),
        safety=("Take a database backup before broad maintenance or upgrades.", "Provider deletion requires a fresh preview, zero surviving managed-link dependencies and one exact Real-Debrid torrent match."),
        related=("backups", "logs"),
    ),
    _topic(
        "logs", "Unified Logs & performance diagnosis", "Operations",
        "Unified Logs combines ArrNexus events with known-error explanations and records slow route timings introduced to make performance problems measurable.",
        prerequisites=("Sign in."),
        setup=("No setup. External log sources may require their own connector configuration."),
        usage=("Filter by source/event/level. Search source=performance or event=slow_request to find routes exceeding the threshold.", "Use request_failed to locate exceptions that caused HTTP failures."),
        success=("A problem can be tied to a route/service/action instead of guessed from UI latency."),
        troubleshooting=("If a page feels slow but has no slow_request entry, inspect browser/network latency and the X-ArrNexus-Elapsed-Ms response header."),
        safety=("Sanitize raw logs before sharing publicly; use the diagnostics bundle when possible."),
    ),
    _topic(
        "settings", "General Settings", "Administration",
        "Settings manages application branding/public URL, SMTP, users, paths, music application credentials, policy, acquisition, notifications, backups, diagnostics and update source.",
        prerequisites=("Administrator access."),
        setup=("Configure only the sections your deployment uses. Most normal state is stored under /data rather than a large .env file."),
        usage=("Save one section at a time and verify the related feature before changing another major subsystem."),
        success=("Saved values persist across container rebuilds because ./data is preserved."),
        troubleshooting=("If a secret field shows blank after reload, that can be intentional masking; the page should indicate configured state.", "If settings vanish after an upgrade, confirm the old data directory was copied/mounted into the new release."),
        safety=("Back up /data before major version upgrades."),
        related=("notifications", "backups", "updates", "language-guard", "music-api-settings"),
    ),
    _topic(
        "language-guard", "Language Guard & rejected-source cleanup", "Administration",
        "Language Guard uses ffprobe against actual stream metadata before a source is linked. v10.4 treats undefined/unknown audio tags as Manual review rather than proof of non-English and supports a fingerprint-bound administrator English override.",
        prerequisites=("The container image includes ffmpeg/ffprobe and the media source is visible in the active namespace.",),
        setup=("English audio is required by default; English subtitles are optional by default.",),
        usage=("Use Item Review for one source or DMM Inbox actions to Check selected languages, Check all unchecked or Force re-check all.", "A cached result from an older policy is labelled Re-check required.", "Block import when language metadata is unknown controls whether Manual-review media is held or allowed through; either way uncertainty never authorizes provider deletion.", "If an old encode has undefined language metadata but you have verified it is English, an administrator can Mark this source as English; the override is bound to the exact source fingerprint.", "Confirmed rejected RD sources can be removed individually or in a selected cleanup job."),
        success=("Confirmed non-English failures display Language rejected.", "`und`, blank, mixed/unknown tags and probe failures become Manual review and never authorize deletion.", "A manual English override expires automatically when the source fingerprint changes.", "After a successful exact RD deletion ArrNexus invalidates DMM/Inbox state so the removed source disappears cleanly."),
        troubleshooting=("Filename language tags are not enough; if ffprobe cannot access the actual path, fix namespace/mount visibility.", "If cleanup is blocked, inspect the job result for a surviving symlink dependency, stale policy result, disconnected RD account or ambiguous provider identity."),
        safety=("Rejected-source cleanup never uses fuzzy title matching.", "Every destructive action rechecks the current policy result, source fingerprint, surviving managed links and exact provider identity at apply time."),
    ),
    _topic(
        "archived-media", "Archived Media Recovery & RAR sources", "Library & automation",
        "Archived Media Recovery scans the DMM __all__ tree for RAR/multipart RAR sets that the normal video scanner cannot see. v10.4.4 runs archive inspection in a background job for very large cloud-backed RARs, verifies every video member independently, and feeds recovered source packs back into the normal DMM Inbox.",
        prerequisites=("The RAR source is visible under the configured DMM source root.", "The v10.4+ container includes a supported 7zip/unrar extractor.", "The recovered media source root must be DUMB-visible so Sonarr/Jellyfin can resolve recovered media; it is not the final library."),
        setup=("Open Archived Media from Library & automation or Maintenance.", "Configure the DUMB-visible recovered-media source root, per-job media size ceiling and optional TMDb API key."),
        usage=("Scan __all__ for archives.", "Start Inspect. Large archives are catalogued in a background job so reverse proxies such as Cloudflare do not time out; completed catalogues reopen from cache.", "For ambiguous names such as season-4_202405.rar, search TMDb and choose the exact movie/TV identity.", "Run Verify media files as a background job. Only recognised video members are tested.", "Return to the archive, choose the verified video members you want and recover them. Failed/unverified members cannot be selected.", "Open the recovered source in Item Review for Language Guard, TV recovery and Sonarr/Radarr import."),
        success=("Multipart RAR sets appear once using their first volume.", "A partial archive can still expose independently verified media members.", "Recovered top-level folders become normal Inbox source packs and group with provider packs for the same series.", "Only selected verified video files are persisted; XML, SQLite, artwork, nested archives and torrent padding are ignored.", "Recovered files pass listed-size and ffprobe video validation before commit.", "TMDb identity drives canonical title/filename previews without renaming the read-only provider source."),
        troubleshooting=("Passworded archives and nested-only archives stay Manual review.", "A CRC/data-failed member stays disabled while other verified members remain recoverable.", "If no extractor is available, rebuild the v10.4+ container image.", "If recovery is blocked for space, choose a larger DUMB-visible recovered-media source root or free space."),
        safety=("Nothing is extracted automatically during normal DMM scanning.", "Only independently verified video members can be recovered.", "Path traversal, archive-created symlinks, unsafe paths, source fingerprint changes and over-limit plans are refused.", "The original provider archive is retained."),
        related=("dmm-inbox", "item-review", "archive-rescue", "tv-recovery", "language-guard"),
    ),
    _topic(
        "archive-rescue", "Archive Rescue & Internet Archive", "Library & automation",
        "Archive Rescue finds monitored Sonarr and Radarr gaps, searches the configured Prowlarr Internet Archive indexer, inspects the real .torrent manifest and can hand selected files to Real-Debrid.",
        prerequisites=("A working Prowlarr connection with the Internet Archive Cardigann indexer.", "For Real-Debrid hand-off, a connected RD account."),
        setup=("In Prowlarr enable Internet Archive, keep Search only in title enabled, enable Download using .torrent only / No Magnets for manifest inspection, and prefer downloads descending for established archive results.",),
        usage=("Open Archive Rescue and scan either Sonarr missing shows or Radarr missing movies.", "Use Search Debrid on a missing card to jump into the dedicated Sonarr/Radarr rescue flow, or Search Internet Archive to inspect Archive candidates.", "Review an Archive result before sending it to RD; choose only the torrent files you actually want.", "After RD receives the source it can flow through Decypharr/DMM and the normal import/recovery path."),
        success=("Missing Sonarr shows and Radarr movies produce reviewable Internet Archive candidates, and selected torrent files are accepted by RD without downloading unrelated files."),
        troubleshooting=("If a result only provides a magnet, enable Prowlarr's .torrent-only option so ArrNexus can inspect its file manifest.", "Internet Archive seed counts exposed by the Cardigann definition are not reliable live swarm telemetry."),
        safety=("Archive Rescue never blindly grabs every result or deletes the original source.", "If selected torrent paths cannot be matched exactly to the new RD torrent, ArrNexus removes the just-added RD entry and fails closed."),
        related=("sonarr-rescue", "radarr-rescue", "self-healing", "dmm-inbox", "tv-recovery", "acquisition"),
    ),
    _topic(
        "sonarr-rescue", "Sonarr Rescue & Real-Debrid fallback", "Acquisition",
        "Sonarr Rescue scans monitored series with missing episodes, searches configured torrent indexers directly through Prowlarr, checks Real-Debrid instant availability and lets an administrator explicitly hand a reviewed candidate to RD.",
        prerequisites=("A working Sonarr and Prowlarr connection.", "A connected Real-Debrid account for direct hand-off."),
        setup=("No extra indexer is required beyond the torrent sources already configured in Prowlarr.",),
        usage=("Scan Sonarr.", "Choose Search Debrid candidates for a missing series.", "Prefer exact/high-confidence and RD-cached results.", "Send only the reviewed release you actually want to Real-Debrid."),
        success=("A stuck Sonarr item can be rescued without making ArrNexus auto-grab every search result; Decypharr/DMM exposes the chosen RD source when ready."),
        troubleshooting=("Real-Debrid is a cache/provider API, not a title-search catalogue; Prowlarr supplies discovery and ArrNexus checks RD cache state.", "If no candidates appear, verify the torrent indexers/categories in Prowlarr."),
        safety=("No candidate is sent automatically.", "Policy-rejected releases cannot be handed to RD from Rescue.", "Active Arr downloads are visibly flagged to reduce duplicate acquisitions."),
        related=("radarr-rescue", "archive-rescue", "debrid-dmm", "acquisition"),
    ),
    _topic(
        "radarr-rescue", "Radarr Rescue & Real-Debrid fallback", "Acquisition",
        "Radarr Rescue scans monitored movies with no imported file, searches configured torrent indexers directly through Prowlarr, checks Real-Debrid instant availability and lets an administrator explicitly hand a reviewed candidate to RD.",
        prerequisites=("A working Radarr and Prowlarr connection.", "A connected Real-Debrid account for direct hand-off."),
        setup=("No extra indexer is required beyond the torrent sources already configured in Prowlarr.",),
        usage=("Scan Radarr.", "Choose Search Debrid candidates for a missing movie.", "Review title/year confidence, ArrNexus policy and RD-cache state.", "Send only the chosen torrent to Real-Debrid."),
        success=("A long-wanted Radarr movie can be handed into the existing RD/Decypharr/DMM pipeline without relying on Radarr to accept the release first."),
        troubleshooting=("If results are broad, include the movie year in the source metadata and inspect the confidence badge.", "If no candidates appear, verify Prowlarr movie categories and torrent indexers."),
        safety=("No candidate is sent automatically.", "Policy-rejected releases cannot be handed to RD from Rescue.", "Active Arr downloads are visibly flagged to reduce duplicate acquisitions."),
        related=("sonarr-rescue", "archive-rescue", "debrid-dmm", "acquisition"),
    ),
    _topic(
        "tv-recovery", "Advanced TV Recovery & combined-season splitting", "Library & automation",
        "Advanced TV Recovery analyses every TV video for combined seasons or joined episodes. Filenames are evidence rather than truth: Sonarr season counts, TMDb season counts/runtimes and ffprobe duration are combined before import.",
        prerequisites=("ffmpeg/ffprobe are available.", "The TV source is visible to ArrNexus.", "TMDb identity is recommended for recovered/archive sources so episode runtimes are available."),
        setup=("Keep the recovered-media output root on a DUMB-visible path such as /mnt/debrid/arrnexus-extracted.",),
        usage=("Analyse a TV source.", "Normal single episodes are marked no-split.", "Explicit ranges such as S03E06-7 are preserved and offered as E06-E07.", "A nominal single episode whose runtime is about 2x/3x the TMDb typical runtime is flagged as a possible joined file.", "Sonarr supplies episode counts when the series is owned; TMDb fills counts when Sonarr is not matched and supplies runtime evidence.", "Runtime-estimated boundaries require explicit confirmation; chapter-perfect plans remain higher confidence.", "Split outputs use FFmpeg stream copy where possible and are ffprobe-verified."),
        success=("Generated files have Sonarr-style SxxExx names and remain under the DUMB-visible recovered-media tree.", "Recovered combined/joined originals are retained under .arrnexus-originals and hidden from future Inbox scans."),
        troubleshooting=("If runtime metadata is unavailable, resolve the exact TMDb identity and analyse again.", "Equal-runtime estimates are still estimates; intros, adverts or unequal episode lengths require review.", "A symlink cannot point to a segment of a file, so split episodes consume real recovered-media storage."),
        safety=("TV import runs this analysis as a pre-Sonarr safety gate for joined/combined media.", "Runtime-only split boundaries are never applied without explicit confirmation.", "The provider RAR/source is retained."),
        related=("archive-rescue", "dmm-inbox", "libraries"),
    ),
    _topic(
        "notifications", "Notifications: ntfy, Gotify, Discord & email", "Administration",
        "Notifications can report ArrNexus events through configured channels and include a test action so credentials/endpoints can be verified before relying on alerts.",
        prerequisites=("A channel endpoint/account. Email notifications also require SMTP settings."),
        setup=("Enable notifications in Settings.", "Configure one or more channels: ntfy server/topic/token, Gotify URL/token, Discord webhook, or email recipient.", "Use Send test notification."),
        usage=("Choose failures-only if you want to suppress routine success messages."),
        success=("The test reaches the intended destination and ArrNexus logs the result."),
        troubleshooting=("Email failures: verify SMTP host/port/STARTTLS/user/password/from address.", "Webhook/token failures: verify the secret and that the ArrNexus container can reach the endpoint."),
        safety=("Webhook URLs and app tokens are credentials; never expose them in screenshots/logs."),
    ),
    _topic(
        "password-recovery", "Password recovery & SMTP", "Accounts & security",
        "Password recovery creates a single-use, time-limited token and emails a reset link through the administrator's SMTP configuration.",
        prerequisites=("The user profile has an email address and SMTP is configured under Settings."),
        setup=("Configure SMTP host, port, username/password, From address and STARTTLS as required by your provider.", "Set the public ArrNexus URL when using a reverse proxy so reset links use the public HTTPS address.", "Use Forgot password on the login page and enter the saved profile email."),
        usage=("Open the emailed link within 30 minutes and choose a new password."),
        success=("The reset page accepts the one-time token and the new password works at login."),
        troubleshooting=("No email: inspect Unified Logs and SMTP settings; ArrNexus intentionally does not reveal whether an address exists.", "Wrong internal URL in email: set/verify the public URL/reverse-proxy forwarded host/proto."),
        safety=("Reset tokens are single-use and expire. Connected service credentials are not changed by an ArrNexus password reset."),
    ),
    _topic(
        "backups", "Backups, sanitized config & diagnostics", "Administration",
        "ArrNexus can create rolling SQLite backups, export/import non-secret configuration and generate a sanitized diagnostics bundle.",
        prerequisites=("Administrator access and writable /data."),
        setup=("Set automatic backup enabled/retention under Settings.", "Create a manual backup before major upgrades."),
        usage=("Download a database backup when you need a full ArrNexus-state restore.", "Use sanitized config export/import for portable non-secret settings.", "Use Diagnostics for support because it masks known secrets."),
        success=("Backup files appear with size/time and restore/export operations complete without exposing credentials."),
        troubleshooting=("If backup creation fails, check /data permissions and free space."),
        safety=("Database backups are private even if UI secrets are masked; they may contain encrypted/protected application state. Do not publish them."),
    ),
    _topic(
        "updates", "Native updates, release ZIPs & rollback", "Administration",
        "ArrNexus v10 can discover newer GitHub Releases, verify the release checksum, back up the live SQLite database, run the complete regression validator, stage the new runtime and restart itself without Portainer or Docker-socket access.",
        prerequisites=("The first move to v10 is a normal Docker rebuild because v10 introduces the self-update bootstrap.", "Future in-app updates require outbound HTTPS access to GitHub Releases and a release containing both an ArrNexus ZIP and matching .sha256 asset."),
        setup=("Keep Fudmonk95/ArrNexus as the update repository unless you deliberately maintain your own fork.", "Select Stable/Beta/Development under Settings → Diagnostics & updates.", "When an update notification appears, review the target version and press Install update."),
        usage=("ArrNexus downloads the release, refuses non-HTTPS assets, verifies SHA-256, blocks unsafe ZIP traversal paths, creates a SQLite backup and validates the staged source before switching runtime.", "The browser watches update progress and reloads automatically once the new /api/health reports the target version.", "The v10 bootstrap keeps previous runtimes under /data/runtime/releases so a newly activated runtime that cannot become healthy can be rolled back automatically."),
        success=("Update status progresses through download, verify, backup, dependencies, validation, staging and restart.", "The page reloads with the new ArrNexus version while users/connections/providers remain present because /data is persistent."),
        troubleshooting=("If Install is disabled, confirm the GitHub Release includes both the ArrNexus ZIP and .sha256 asset.", "If a future release needs Docker/OS/bootstrap changes, perform a normal container rebuild for that release instead of bypassing the safety boundary.", "If the new runtime cannot become healthy, inspect update status/logs; the bootstrap should return to the previous staged runtime."),
        safety=("ArrNexus never needs the Docker socket for ordinary v10+ application updates.", "The live database is not replaced by release files; a transaction-safe SQLite backup is created first.", "Do not disable checksum or validator failures to force an update through."),
    ),
    _topic(
        "providers-sdk", "Community music/provider JSON", "Administration",
        "The community catalogue/provider SDK uses JSON/data definitions rather than arbitrary Python execution.",
        prerequisites=("A provider JSON definition you trust and have reviewed."),
        setup=("Install the JSON from the supported Settings upload form.", "Confirm external search URLs are real HTTPS destinations and not documentation placeholders."),
        usage=("The provider appears as a labelled catalogue/discovery source where supported."),
        success=("Provider searches build only the expected bounded URL/data request."),
        troubleshooting=("example.com/example.invalid URLs are intentionally rejected.", "Malformed JSON should be fixed rather than bypassing validation."),
        safety=("Review third-party URLs and never embed private credentials directly in a community JSON file intended for sharing."),
    ),
    _topic(
        "profile", "Profile", "Accounts & security",
        "Profile stores per-user display name, email and password. Product-wide visual styling is fixed; the old theme gallery is intentionally removed.",
        prerequisites=("Signed-in user."),
        setup=("Set an email if you want password recovery to work."),
        usage=("Update display name/email or enter a new password; leave password blank to keep the current one."),
        success=("Changes are reflected in the sidebar/account and survive restart."),
        troubleshooting=("If password recovery fails, verify both profile email and administrator SMTP settings."),
        safety=("Do not share accounts; use separate users and permissions."),
    ),
    _topic(
        "security", "Security & privacy model", "Accounts & security",
        "ArrNexus is designed for a private self-hosted control plane: secret settings are masked, diagnostics are sanitized, source media is preserved by non-destructive workflows and community extensions are data-only.",
        prerequisites=("Deploy behind appropriate network/reverse-proxy access controls for your environment."),
        setup=("Use HTTPS when exposing ArrNexus remotely.", "Create separate user accounts and keep admin access limited.", "Back up /data securely."),
        usage=("Treat any raw API key/token/webhook/backup as sensitive even if ArrNexus normally masks it."),
        success=("Public landing/help/release export contain no private library/IP/path/credential state; private operational pages require authentication."),
        troubleshooting=("If a credential appears in UI/logs/diagnostics, treat it as a security bug and rotate the exposed secret."),
        safety=("Do not expose ArrNexus directly to the Internet without understanding your reverse proxy and authentication boundary."),
    ),
    _topic(
        "performance", "Performance troubleshooting", "Operations",
        "ArrNexus measures route time with Server-Timing and X-ArrNexus-Elapsed-Ms and logs requests above the slow threshold so optimisation can target the actual expensive route.",
        prerequisites=("A page that feels slow enough to investigate."),
        setup=("No setup required."),
        usage=("Use the application normally, then open Unified Logs and filter source=performance/event=slow_request.", "Compare repeated timings after caches warm; one first-load result is not enough to diagnose a route."),
        success=("You can identify whether latency is in /maintenance, /music/artist, /inbox, /readiness, InfiniDysk or another route and then test its upstream dependency."),
        troubleshooting=("If server time is low but browser navigation is slow, inspect browser/network/reverse-proxy latency.", "If server time is high, test the integrations used by that route and look for upstream timeout patterns."),
        safety=("Avoid solving slowness by disabling authentication/validation or reducing safety timeouts globally."),
        related=("logs",),
    ),
    _topic(
        "release-management", "Public download & deployment methods", "Start here",
        "The public landing page can export a clean source-only ZIP from the running build and documents ZIP, Git clone, Portainer Git stack and future official-container deployment paths.",
        prerequisites=("For the built-in exporter, a running ArrNexus instance."),
        setup=("Use /download/latest for the source ZIP and /download/latest.sha256 for its digest.", "For Git deployment, point Portainer at the public repository and docker-compose.yml when the project is published.", "GHCR examples remain templates until an official ArrNexus image is actually published."),
        usage=("Validate a downloaded source release before Docker build; preserve data separately during upgrades."),
        success=("The exported ZIP contains source/docs only and excludes runtime/private state."),
        troubleshooting=("If an unofficial image appears before an official release, do not assume it is trusted because it uses the ArrNexus name."),
        safety=("Public exports must never contain /data, databases, .env, backups, virtualenvs, bytecode or secrets."),
    ),
]

TOPICS_BY_SLUG = {topic["slug"]: topic for topic in TOPICS}

# Prefix order matters: most specific first.
ROUTE_TOPIC_PREFIXES = [
    ("/api/dashboard", "dashboard"),
    ("/api/jobs", "jobs"),
    ("/api/jobs-active", "jobs"),
    ("/api/logs", "logs"),
    ("/api/ecosystem", "ecosystem"),
    ("/api/infinidysk", "infinidysk"),
    ("/api/scraping", "acquisition"),
    ("/api/debrid", "debrid-dmm"),
    ("/api/aiostreams", "aiostreams"),
    ("/api/lists", "lists"),
    ("/api/aiometadata", "aiometadata"),
    ("/maintenance/archives", "archived-media"),
    ("/archive-rescue", "archive-rescue"),
    ("/sonarr-rescue", "sonarr-rescue"),
    ("/radarr-rescue", "radarr-rescue"),
    ("/tv-recovery", "tv-recovery"),
    ("/api/health", "getting-started"),
    ("/music/settings", "music-api-settings"),
    ("/music/spotify", "spotify"),
    ("/music/artist", "music-hub"),
    ("/music", "music-hub"),
    ("/aiostreams", "aiostreams"),
    ("/lists", "lists"),
    ("/aiometadata", "aiometadata"),
    ("/providers", "providers"),
    ("/infinidysk", "infinidysk"),
    ("/decypharr", "decypharr"),
    ("/indexers", "indexers"),
    ("/debrid", "debrid-dmm"),
    ("/inbox", "dmm-inbox"),
    ("/item", "item-review"),
    ("/bulk-import", "dmm-inbox"),
    ("/import", "dmm-inbox"),
    ("/undo", "dmm-inbox"),
    ("/libraries", "libraries"),
    ("/browser", "libraries"),
    ("/rules", "routing"),
    ("/self-healing", "self-healing"),
    ("/quality-lab", "quality-lab"),
    ("/queue", "queue"),
    ("/timeline", "timeline"),
    ("/jobs", "jobs"),
    ("/discover", "discover"),
    ("/scraping", "acquisition"),
    ("/problems", "problem-centre"),
    ("/maintenance/provider-cleanup", "maintenance"),
    ("/maintenance/consolidation", "maintenance"),
    ("/maintenance", "maintenance"),
    ("/logs", "logs"),
    ("/ecosystem", "ecosystem"),
    ("/readiness", "readiness"),
    ("/arrs", "connections"),
    ("/settings/connection", "connections"),
    ("/media-servers", "media-servers"),
    ("/settings/notifications", "notifications"),
    ("/settings/backup", "backups"),
    ("/settings/export-config", "backups"),
    ("/settings/import-config", "backups"),
    ("/diagnostics", "backups"),
    ("/settings/update", "updates"),
    ("/settings/language", "language-guard"),
    ("/settings/provider-plugin", "providers-sdk"),
    ("/settings", "settings"),
    ("/profile", "profile"),
    ("/onboarding", "onboarding"),
    ("/setup", "onboarding"),
    ("/forgot-password", "password-recovery"),
    ("/reset-password", "password-recovery"),
    ("/login", "authentication"),
    ("/logout", "authentication"),
    ("/download", "release-management"),
    ("/api/public/release", "release-management"),
    ("/api/update-install", "updates"),
    ("/api/update-status", "updates"),
    ("/api/update-check", "updates"),
    ("/dashboard", "dashboard"),
    ("/", "getting-started"),
]


def topic_for_path(path: str) -> str:
    value = str(path or "/")
    for prefix, slug in ROUTE_TOPIC_PREFIXES:
        if prefix == "/":
            if value == "/":
                return slug
            continue
        if value.startswith(prefix):
            return slug
    return "getting-started"


def get_topic(slug: str | None) -> dict[str, Any] | None:
    return TOPICS_BY_SLUG.get(str(slug or ""))


def categories() -> list[tuple[str, list[dict[str, Any]]]]:
    order: list[str] = []
    grouped: dict[str, list[dict[str, Any]]] = {}
    for topic in TOPICS:
        category = topic["category"]
        if category not in grouped:
            order.append(category)
            grouped[category] = []
        grouped[category].append(topic)
    return [(name, grouped[name]) for name in order]
